language: rust
rust:
- stable
- beta
- nightly
notifications:
  email:
  - mitchell.nordine@gmail.com
os:
- osx
- linux
before_script:
- rustc --version
- cargo --version
- rustup component add rustfmt
- if [ "$TRAVIS_OS_NAME" = linux ]; then rustup target add x86_64-apple-darwin; fi
script:
- if [ "$TRAVIS_OS_NAME" = linux ]; then curl -sL https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.13.sdk.tar.xz | tar -Jxf -; export COREAUDIO_SDK_PATH="$PWD/MacOSX10.13.sdk"; fi
- RUSTFMT=rustfmt cargo build --verbose --target=x86_64-apple-darwin
- if [ "$TRAVIS_OS_NAME" = osx ]; then RUSTFMT=rustfmt cargo test --verbose; fi
- if [ "$TRAVIS_OS_NAME" = osx ]; then rustup target add aarch64-apple-ios x86_64-apple-ios; for i in aarch64-apple-ios x86_64-apple-ios; do RUSTFMT=rustfmt cargo build --verbose --target=$i; done; fi
